#!/usr/bin/python3
# randomimport carousel.log as log
import os
# import itertools
# import collections
# import glob
# import 

import carousel
from carousel import log

log.init( '/tmp/carousel_photos.log')

ROOT = os.path.dirname(os.path.abspath(__file__))
PHOTOROOT = os.path.join(ROOT, "photos")
FILELIST = os.path.join( ROOT, "photolist.txt") 

try:
    my_env = os.environ
    my_env["DISPLAY"] = ":0"

    supervisor = carousel.Supervisor(PHOTOROOT, FILELIST, carousel.buildPhotoList)
    process = ["/usr/bin/feh","-Y","-F","-Z","-D","5","-f",FILELIST ]
    supervisor.startProcess( process )
    supervisor.monitor()
except Exception as e:
    log.exception(e)


