#!/usr/bin/python3
from carousel_common import *

ROOT = os.path.dirname(os.path.abspath(__file__))
FILELIST = os.path.join( ROOT, "musiclist.txt") 
music = os.path.join(ROOT, "music")

   
def buildMusicList():
    files = glob.glob('{}/*.ON/*'.format(music))
    return files

supervisor = Supervisor(FILELIST, buildMusicList)

supervisor.startProcess(['/usr/bin/mpv', '--really-quiet', '--loop=inf', '--playlist={}'.format(FILELIST)])#alternative:  ['/usr/bin/mplayer', '-nolirc', '-msglevel', 'all=3', '-loop', '0', '-playlist', FILELIST]
supervisor.monitor()



