#!/usr/bin/python3
import logging as log
from carousel_common import *

log.basicConfig(level=log.DEBUG,
                    format='%(asctime)s %(levelname)s %(message)s',
                    filename='/tmp/carousel_music.log',
                    filemode='w')

ROOT = os.path.dirname(os.path.abspath(__file__))
FILELIST = os.path.join( ROOT, "musiclist.txt") 
music = os.path.join(ROOT, "music")

   
def buildMusicList():
    files = glob.glob('{}/*.ON/*'.format(music))
    return files

supervisor = Supervisor(FILELIST, buildMusicList)

supervisor.startProcess(['/usr/bin/mpv', '--really-quiet', '--loop=inf', '--playlist={}'.format(FILELIST)])#alternative:  ['/usr/bin/mplayer', '-nolirc', '-msglevel', 'all=3', '-loop', '0', '-playlist', FILELIST]
supervisor.monitor()



